image: archlinux
oauth: pages.sr.ht/PAGES:RW
shell: true
tasks:
  - install-dependencies: |
      # Install micromamba.
      curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      ./bin/micromamba shell -s posix hook >> ~/.buildenv

      # Install Poetry.
      curl -sSL https://install.python-poetry.org | python3 -
      echo 'export PATH="/home/build/.local/bin:$PATH"' >> ~/.buildenv

      # Source buildenv to access micromamba and Poetry in this session.
      . ~/.buildenv

      # Create the brodie.srht.site Mamba environment defined by environment.yml.
      cd brodie.srht.site
      micromamba create --file environment.yml --yes

      # Install Python dependencies.
      micromamba run --name brodie.srht.site poetry install
  - build: |
      cd brodie.srht.site/site
      micromamba run --name brodie.srht.site poetry run nikola build
  - package: |
      cd brodie.srht.site/site/output
      tar -cvz . > ~/site.tar.gz
      # Complete build early if this is not the master branch.
      if [ "$(git rev-parse master)" != "$(git rev-parse HEAD)" ]; then \
          complete-build; \
      fi
  - upload: |
      acurl -f https://pages.sr.ht/publish/brodie.srht.site -Fcontent=@site.tar.gz
      acurl -f https://pages.sr.ht/publish/brodie.id.au -Fcontent=@site.tar.gz
