[tool.poetry]
name = "brodie.id.au"
version = "0.1.0"
description = "My website."
authors = []

[tool.poetry.dependencies]
python = "^3.10"
Sphinx = "^5.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
